workflows:
  ios-native-quick-start:
    name: iOS Native
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: API 4
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.cherevan.lasttimetracker
      vars:
        BUNDLE_ID: "com.cherevan.lasttimetracker"
        XCODE_PROJECT: "LastTime.xcodeproj"
        XCODE_SCHEME: "LastTime"
        APP_STORE_APPLE_ID: 6760702173
      xcode: latest
    scripts:
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles

      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --project "$CM_BUILD_DIR/$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
      - name: Increment build number
        script: |
          cd $CM_BUILD_DIR
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          NEW_BUILD_NUMBER=$(($LATEST_BUILD_NUMBER + 1))
          agvtool new-version -all $NEW_BUILD_NUMBER
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      email:
        recipients:
          - user_1@example.com
          - user_2@example.com
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - group name 1
          - group name 2
        submit_to_app_store: false
